// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrqg31yArYxNwZsBRMTdPRYUf2ORWN14',
    appId: '1:671807060347:web:8a3db12379de840e02a5de',
    messagingSenderId: '671807060347',
    projectId: 'nalaseva-pbmb15',
    authDomain: 'nalaseva-pbmb15.firebaseapp.com',
    storageBucket: 'nalaseva-pbmb15.firebasestorage.app',
    measurementId: 'G-K8FGS744LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeXWQgRDuE_lUY1gCNw33-cfTVbcD0No',
    appId: '1:671807060347:android:6b3ed9d3f487998e02a5de',
    messagingSenderId: '671807060347',
    projectId: 'nalaseva-pbmb15',
    storageBucket: 'nalaseva-pbmb15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzRjgxkhGfTmSqsObEi4BKEpgtSXrUUk',
    appId: '1:671807060347:ios:230f16c0ec9a4d8302a5de',
    messagingSenderId: '671807060347',
    projectId: 'nalaseva-pbmb15',
    storageBucket: 'nalaseva-pbmb15.firebasestorage.app',
    iosBundleId: 'com.example.nalaseva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABzRjgxkhGfTmSqsObEi4BKEpgtSXrUUk',
    appId: '1:671807060347:ios:230f16c0ec9a4d8302a5de',
    messagingSenderId: '671807060347',
    projectId: 'nalaseva-pbmb15',
    storageBucket: 'nalaseva-pbmb15.firebasestorage.app',
    iosBundleId: 'com.example.nalaseva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcrqg31yArYxNwZsBRMTdPRYUf2ORWN14',
    appId: '1:671807060347:web:bfa6b5cadfdf11a402a5de',
    messagingSenderId: '671807060347',
    projectId: 'nalaseva-pbmb15',
    authDomain: 'nalaseva-pbmb15.firebaseapp.com',
    storageBucket: 'nalaseva-pbmb15.firebasestorage.app',
    measurementId: 'G-LBSVD2EFVB',
  );
}
